### ISSUE TITLE
More energies 

### ISSUE THREAD

**Issue by zhubonan** [aiida-vasp/parsevasp#33]
At the moment the parser only pulls out `energy_no_entropy`. 

The other two are also important, especially when working with metals and testing out different smearing schemes / sigma. 

https://github.com/aiida-vasp/parsevasp/blob/cdd42b691b8f124f5611763c8f6d4deff1007d82/parsevasp/vasprun.py#L2904-L2911

Also `aiida-vasp` only has `energy_no_entropy` as a result... and the total energies dictionary only have one single entry.

```
- symmetries: {'num_space_group_operations': {'dynamic': [], 'static': []},
 'point_group': {'dynamic': [], 'static': []},
 'primitive_translations': []}
- maximum_force: 0.023121134707029
- maximum_stress: 0.66971666710401
- total_energies: {'energy_no_entropy': -250.6043836}

```

**Comment by espenfl** [comment]
Thanks for the comment, please see https://github.com/aiida-vasp/aiida-vasp/issues/356#issuecomment-642481543

**Comment by espenfl** [comment]
Closing this and putting it into #34. Thanks @zhubonan.
