### ISSUE TITLE
make a bug fix release for #62

### ISSUE THREAD

**Issue by zhubonan** [aiida-vasp/parsevasp#63]
A bug fix release should be made for #62 to take effect. 

The develop branch of aiida-vasp will use the `truncated` tags for calculation status, and the incorrect results may be recorded if `parsevasp` is not updated. 

After this, https://github.com/aiida-vasp/aiida-vasp/pull/412 will increase the minimum `parsevasp` version requirement.

**Comment by espenfl** [comment]
Fixed in #64 by #62.
