### ISSUE TITLE
IncarItem doesn't have ERROR_MESSAGES but used in

### ISSUE THREAD

**Issue by atztogo** [aiida-vasp/parsevasp#68]
At current `develop` branch (`cd1cd18dea`).

`IncarItem` doesn't have `self.ERROR_MESSAGES` and similar objects but they are used in it. Is it expected to be passed from `Incar` class?

**Comment by espenfl** [comment]
@atztogo Thanks. Yes I also noticed this yesterday when I got some errors in that class. I will fix it today (in develop). Do you need a release?

**Comment by atztogo** [comment]
No release needed. Update of `develop` is fine. I have no objection. Thanks!

**Comment by espenfl** [comment]
Closed by #69. Thanks for raising. See also #70.
